name: Daily Job Feed Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 8:00 AM IST
  workflow_dispatch:

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll override with token manually

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run fetch_jobs.py
        run: python3 fetch_jobs.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add daily_jobs.json
          git commit -m "Auto-update daily_jobs.json" || echo "No changes to commit"
          git pull --rebase origin main || echo "No remote changes to rebase"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
